name: Q&A
on:
    pull_request_target:
defaults:
    run:
        shell: bash
jobs:
    call-qa:
        uses: heyframe/recipes/.github/workflows/callable-qa.yml@main
        with:
            contrib: true
        secrets:
            token: ${{ secrets.CI_COMMIT_PAT }}
